language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DkBePoZzUSZ+bLj3Rl20yq5HFMIXcX6w+1dlXZfZ9ZC3a2jXiWZB2LOMFtRTB9RtfZ0t7SPzRv0HqMaSus9Y2yWGhwkKur83f8CWv/6QQq9/HKNL8jYEddI1jtTAsvs+KmJZdxvv/ML3XDQGjPAVuW7GZ+IloAJLjdKYAtIXwCp6hcgqy43EH1l8Z/+vZOLj1YEA78ITMaIbBL+fnWRAK8XDoXv2GA/5cw6iPHEfq/mS/bUcHojBttjUzggi7fUkOHd57LdvAPsYzkiv2Zg/GzZuE5T5DlpfuPBBvWr7T2rMSnC4vdE/gjyvcJLKC26fk5p03YAHdbMjEAJg1OfgLmUW/GhOFDidg29BjIh1HE4JLjmbvsXXyZtbxYQLptzlZEy6OfJ/n7e0XEEHeI/dwTFnoY0Y3N2UWZLjzNPupg5+7yicrbJzxc1ntrhT5mebMT7qdVhWKStx2A7qnzkfLaIcEb/cfm9YW+ax9k3NvAhDt8+70SSJB3A9u8DYoqTb+exNdenqgtRZu9c2xWUkrDXCf+TH1nroYL557Lxe5RadtdQ1K0q6Hsjb6eFOBx2zOAzeOyqxp7IA5wtKaOS2v4S2tvgwh0GtO5k0QDCfqPPNYWLkbH946mAWbn9eomjEBwJlGabMmIE9esNRprOxkfmB2qmHuN57ftMCEXYmXk0=
  file:
    - "mdast-util-compact.js"
    - "mdast-util-compact.min.js"
  on:
    tags: true
    node: '9.0'
